# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteSingUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('cep', models.CharField(blank=True, max_length=15)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('number', models.CharField(blank=True, max_length=5, null=True)),
                ('complement', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('photo', models.URLField(blank=True)),
                ('cnpj', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('site', models.CharField(max_length=100)),
                ('social', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
