# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='is_deferred',
            field=models.CharField(choices=[('DEFERIDO', 'DEFERIDO'), ('EM ANÁLISE', 'EM ANÁLISE'), ('INDEFERIDO', 'INDEFERIDO')], default='EM ANÁLISE', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('ACEITO', 'ACEITO'), ('EM ANÁLISE', 'EM ANÁLISE'), ('RECUSADO', 'RECUSADO')], default='EM ANÁLISE', max_length=100),
        ),
    ]
