# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Match'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='cnpj',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='institute',
            name='site',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='institute',
            name='social',
            field=models.CharField(max_length=100),
        ),
    ]
