# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonuser',
            name='address',
            field=models.CharField(default='Nao Informado', max_length=100),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='cep',
            field=models.CharField(default='Nao Informado', max_length=15),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='city',
            field=models.CharField(default='Nao Informado', max_length=100),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='complement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='district',
            field=models.CharField(default='Nao Informado', max_length=100),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='number',
            field=models.CharField(default='Nao Informado', max_length=5),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='state',
            field=models.CharField(default='Nao Informado', max_length=20),
        ),
    ]
