# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
