# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 23:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('Eletronicos', 'Eletronicos'), ('Vestimentas', 'Vestimentas'), ('Alimentos', 'Alimentos'), ('Higiene', 'Higiene'), ('Mobilia', 'Mobilia'), ('Brinquedos', 'Brinquedos'), ('Papelaria', 'Papelaria'), ('Outros', 'Outros')], max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=300)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Necessidade',
                'verbose_name_plural': 'Necessidades',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='requirement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Requirement'),
        ),
    ]
