# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171207_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonuser',
            options={'verbose_name': 'Doador', 'verbose_name_plural': 'Doadores'},
        ),
    ]
