# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171130_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
