# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auditor'),
        ('app', '0002_donation'),
    ]

    operations = [
    ]
