# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171202_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Item'),
        ),
        migrations.AlterField(
            model_name='match',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Requirement'),
        ),
    ]
