# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171202_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='audit',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Item'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='new_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
