# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171129_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='cep',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='number',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='commonuser',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='institute',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='institute',
            name='cep',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='institute',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='institute',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='institute',
            name='number',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='institute',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='institute',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
