# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171201_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
